package seclogin.math;

import seclogin.Password;
import java.math.BigInteger;
import javax.crypto.SecretKey;
import seclogin.Crypto;

/**
 * A pseudorandom function family over Z_q:
 * AES with key generated by PBKDF2-HMAC-SHA1 from the provided salt and password.
 */
public class G {

    private final SecretKey key;
    private final Zq zq;

    private G(SecretKey key, Zq zq) {
        this.key = key;
        this.zq = zq;
    }

    public static G forSaltedPassword(byte[] salt, Password pwd, Zq zq) {
        return new G(Crypto.generateAes128Key(salt, pwd.asChars()), zq);
    }

    public BigInteger of(BigInteger input) {
        return new BigInteger(Crypto.aes128Encrypt(key, input.toByteArray())).mod(zq.q);
    }
}
