package seclogin.math;

import seclogin.Crypto;

import javax.crypto.SecretKey;
import java.math.BigInteger;

/**
 * A PRF over Z_q, keyed on a salted password.
 *
 * Implemented by delegating to AES-128 with key generated by
 * PBKDF2-HMAC-SHA1 from the provided salt and password.
 */
public class PasswordBasedPRF {

    private final SecretKey key;
    private final BigInteger q;

    private PasswordBasedPRF(SecretKey key, BigInteger q) {
        this.key = key;
        this.q = q;
    }

    public static PasswordBasedPRF forSaltedPassword(byte[] salt, String password, BigInteger q) {
        return new PasswordBasedPRF(Crypto.deriveAes128Key(salt, password.toCharArray()), q);
    }

    public BigInteger of(int input) {
        return new BigInteger(Crypto.aes128Encrypt(key, BigInteger.valueOf(input).toByteArray())).mod(q);
    }
}
